### ISSUE TITLE
Incorrect paths to data in activation-based-fem.srn5

### ISSUE THREAD

**Issue by a-y-khan** [SCIInstitute/FwdInvToolkit#7]
The activation-based-fem.srn5 network has paths that need to be fixed. Also, sub-paths from **_%SCIRUNDATADIR%**_ need to be consistent across toolkit networks (**_%SCIRUNDATADIR%/ToolKits/FwdInvToolbox**_ changed to **_%SCIRUNDATADIR%/Data**_).

**Comment by dcwhite** [comment]
Should be assigned to @jessdtate but he's not in the collaborator list--yet.
